### ISSUE TITLE
Allow customized mouse key bindings

### ISSUE THREAD

**Issue by dmarcotte** [dmarcotte/easy-move-resize#2]
For both move and resize, offer a preference where users can choose which modifier keys + which mouse button triggers the action

**Update:** modifier keys can now be configured, but customized mouse button bindings still need to be implemented.  I have updated the issue title to reflect this.

**Comment by peterjmag** [comment]
+1! Clicking and dragging with two fingers on a trackpad is a bit difficult, so I'd love to be able to set my own key bindings.

And as an aside, great work on this! I was really happy stumble across it after watching [this talk by Ryan Florence](https://youtu.be/z5e7kWSHWTg?t=3m), where he uses something similar. (Turns out he actually uses [Zooom/2](http://www.coderage-software.com/zooom/index.html), which is not free or open source, but also looks cool.) I also raved about it a bit on an Apple StackExchange question called [Raise/lower/move/resize windows with mouse + modifier keys](http://apple.stackexchange.com/questions/7549/raise-lower-move-resize-windows-with-mouse-modifier-keys/176682#176682).

**Comment by freshdried** [comment]
+1. I'd want to bind the modifier key to just `Cmd`

**Comment by dmarcotte** [comment]
@cedricbastin would like to see this too (#10)

**Comment by cedricbastin** [comment]
Yes this is a good idea, especially since a right click drag is not possible on a MacBook!
Also it would be nice to show the key binding "Cmd + Ctrl + Drag = Move Window" when clicking on the menu item, because sometimes I forget and get lost in all the keyboard shortcuts I have to remember =)

**Comment by fmaylinch** [comment]
Configurable keys would be cool.

In the meantime, I perform this "ceremony" to resize:

- Hold Ctrl+Cmd
- Place two fingers on your trackpad
- Press (click) with one finger
- Hold the pressure with that finger while dragging the other (which doesn't need to press)

Hope that helps :smile:

**Comment by dmarcotte** [comment]
Progress here: @rajpaulbagga recently sent some pulls that enable custom modifier keys.  Thanks @rajpaulbagga!  Will cut a release soon.

Configurable mouse buttons is still an open issue, but this is a nice step forward.

**Comment by dmarcotte** [comment]
The new release with customizable key bindings is now available: https://github.com/dmarcotte/easy-move-resize/releases/tag/1.1.0

**Comment by jayhlee** [comment]
Just installed and started to use this, as Flexiglass App is no longer supported or working properly on Mac Silicon/Big Sur. Works great! Thanks! Is creating customizable mouse button triggers still on the roadmap?

**Comment by dmarcotte** [comment]
Going to close this in favor of the more focused https://github.com/dmarcotte/easy-move-resize/issues/69
