### ISSUE TITLE
Window gets pushed down while trying to cross the top edge of monitor

### ISSUE THREAD

**Issue by nkgm** [dmarcotte/easy-move-resize#20]
This is an issue with OSX being obsessed about keeping the vertical portion of the window title bar within the bounds of a monitor. The same problem happens with BTT window moving, so wondering if there's a workaround or some hidden system default to deactivate this behavior.

Here is a short description of the problem:
```
+========+ <-- menu bar
|        |
|  mon1  |
+--------+
|  ^^^^  |
|  mon2  |
+--------+
``` 

When dragging a window from `mon2` to `mon1` there appears to be a constant push forcing the window's title bar within the top bound of `mon2`.

**Comment by dmarcotte** [comment]
Hey @nkgm, I unfortunately do not know how to override this behavior.

Since this tool is implemented using the Accessibility API, if you manage to find an OSX setting that'll allow it, then it should get respected.  Apologies that's not much to go on, and feel free to update here if you find more info.
