### ISSUE TITLE
Very slow moving / resizing on Sierra

### ISSUE THREAD

**Issue by schmic** [dmarcotte/easy-move-resize#22]
Hi,

using a Hackintosh here running Sierra with the latest Nvidia drivers.

Whenever I move or resize a window it takes seconds to finish the action. The window is moving slowing to it's new location in multiple steps.

Known issue? Anything I can do to provide more information?

**Comment by dmarcotte** [comment]
Hey @schmic, the performance of the resize is determined by the performance of OSX's accessibility API.  For most apps this is perfectly fine, but on some I've seen it get fairly chunky (the MS Office suite on Mac is the one that pops immediately to mind).

Hopefully that's what you're seeing... if you're having consistent problems across all apps, I'd wonder if the accessibility API is just cranky on your setup.

Going to optimistically close this since in either case our hands are tied, but please chime in again if you think I've missed something here.
