### ISSUE TITLE
Ignore Status bar when using cmd

### ISSUE THREAD

**Issue by xiamaz** [dmarcotte/easy-move-resize#46]
Currenty if using cmd to move windows all cmd+clicks will be captured. Unfortunately cmd+click is also used to reorder the statusbar. If would be great if clicks not resulting in window movements could be passed through to other applications.

**Comment by dmarcotte** [comment]
These clicks are intentionally swallowed for the chosen modifiers since most of the modifier+clicks have side effects like this that don't play nice with moving and resizing (for instance: cmd-option-click on a non-focused window hides the window).  I'd consider a contribution that figures out a good system to have it both ways, but I think for now the current default is correct.  Sorry this messes with your workflow!  Cmd being so useful for non move/size stuff is precisely why it's not the default modifier.
