### ISSUE TITLE
command click conflict on dock 

### ISSUE THREAD

**Issue by icq4ever** [dmarcotte/easy-move-resize#75]
first thank you for this super useful application.

in macOS, in dock, command + click can open location on finder. 
this feature is not working while easy-move-reize enabled.

I'm not sure this is bug or missing. but want to let you know!
thank you again!

**Comment by dmarcotte** [comment]
Thanks for the note @icq4ever!

The modifiers keys you choose are by design swallowed by Easy Move+Resize since passing them through leads to other weird behavior (i.e. alt-click on an inactive window hides the currently active window before activating the clicked window, which is really awkward if `alt` is your move/resize modifier)

Perhaps there's a way to notice times when an event cannot possibly ever result in a move/resize operations and let the event through in those cases?  Could be an interesting contribution for someone to look into in.

For now I'm okay continuing to lean on allowing folks to customize their Easy Move+Resize modifiers to something that doesn't conflict with other shortcuts they like, so going to close this as "expected behavior".  (But, again: thanks for filing!  Hope the app is treating you well)

**Comment by acruise** [comment]
I have a similar issue... Coming from Linux+KDE I've used Alt-Drag for many years, and on my keyboard the Win/Linux Alt key is the same as the Mac Command key... In IDEA you can Cmd-click on symbols to go to their declaration, but EM+R is eating the Cmd-Click... 

Not sure if this would be an easy fix, but I think we should be able to check how many pixels the cursor moved between the button press and release, and if it's below a threshold, treat it as a Mod+click rather than a very small move. :)
