### ISSUE TITLE
May 1 MacOS update requires update

### ISSUE THREAD

**Issue by dvdplm** [dmarcotte/easy-move-resize#91]
When launching Easy Move + Resize I get the following dialog: “Easy Move+Resize.app” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information."

<img width="264" alt="Screenshot 2023-05-02 at 12 34 10" src="https://user-images.githubusercontent.com/18515/235644036-4aef2003-c99a-4761-bb30-1d0a573d0dc2.png">

Note: this is a different issue than what is described [here](https://github.com/dmarcotte/easy-move-resize/issues/79#issuecomment-1109070242).

**Comment by dmarcotte** [comment]
Hi @dvdplm, thanks for the note here.  [The solution here should get you sorted](https://github.com/dmarcotte/easy-move-resize/issues/84#issuecomment-1184946746), but please let me know if it doesn't for whatever reason:  I recently [updated the **troubleshooting** section of the  readme to try and preemptively help folks with this](https://github.com/dmarcotte/easy-move-resize#troubleshooting), so I'd really like to know if there's edge cases I missed.

**Comment by olafurg** [comment]
Hi there. Saw this is more recent than where the solution is listed, so commenting here. The solutions there (open from Applications and the xattr command) don't work for me. I keep getting the warning while the app does have the permissions requested in the Accessibility settings. Am I perhaps missing something? Otherwise, thanks for an excellent app, it's a must-have for me. 🙏

**Comment by dmarcotte** [comment]
Thanks, @olafurg!  I'm glad you're sorted, and it great to hear you've found the app useful.
